"""initial_revision

Revision ID: 34c3743f15ed
Revises: 
Create Date: 2024-07-24 18:19:09.088196+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '34c3743f15ed'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gdrive_file_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_file_file_name'), 'collection_file', ['file_name'], unique=True)
    op.create_index(op.f('ix_collection_file_gdrive_file_id'), 'collection_file', ['gdrive_file_id'], unique=True)
    op.create_index(op.f('ix_collection_file_id'), 'collection_file', ['id'], unique=False)
    op.create_index(op.f('ix_collection_file_timestamp'), 'collection_file', ['timestamp'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collection_file_timestamp'), table_name='collection_file')
    op.drop_index(op.f('ix_collection_file_id'), table_name='collection_file')
    op.drop_index(op.f('ix_collection_file_gdrive_file_id'), table_name='collection_file')
    op.drop_index(op.f('ix_collection_file_file_name'), table_name='collection_file')
    op.drop_table('collection_file')
    # ### end Alembic commands ###
