"""Initial Revision

Revision ID: f6873d006975
Revises: 
Create Date: 2024-07-19 13:48:04.565538+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "f6873d006975"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collection_file",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("file_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("downloaded_at", sa.DateTime(), nullable=True),
        sa.Column("imported_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_collection_file_file_name"), "collection_file", ["file_name"], unique=False)
    op.create_index(op.f("ix_collection_file_id"), "collection_file", ["id"], unique=False)
    op.create_index(op.f("ix_collection_file_timestamp"), "collection_file", ["timestamp"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_collection_file_timestamp"), table_name="collection_file")
    op.drop_index(op.f("ix_collection_file_id"), table_name="collection_file")
    op.drop_index(op.f("ix_collection_file_file_name"), table_name="collection_file")
    op.drop_table("collection_file")
    # ### end Alembic commands ###
